### ISSUE TITLE
diskconf "leave as is" option is broken

### ISSUE THREAD

**Issue by alan-barzilay** [archlinux/archinstall#2220]
Error when using config without diskconfig line:

```
sudo archinstall --config /tmp/user_configuration.json --creds templates/root.json --silent
Testing connectivity to the Arch Linux mirrors...
Traceback (most recent call last):
  File "/home/manjaro/archinstall/venvv/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
             ^^^^^^^^^^^^^^^^^
  File "/home/manjaro/archinstall/venvv/lib/python3.11/site-packages/archinstall/__init__.py", line 291, in run_as_a_module
    importlib.import_module(mod_name)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manjaro/archinstall/venvv/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 250, in <module>
    archinstall.arguments['disk_config'],
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'disk_config'
```

When using diskcinfig: null (ran from ansible)

```
"Traceback (most recent call last):\n  File \"/tmp/venv_archinstall/bin/archinstall\", line 8, in <module>\n    sys.exit(run_as_a_module())\n             ^^^^^^^^^^^^^^^^^\n  File \"/tmp/venv_archinstall/lib/python3.11/site-packages/archinstall/__init__.py\", line 291, in run_as_a_module\n    importlib.import_module(mod_name)\n  File \"/usr/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<frozen importlib._bootstrap>\", line 1204, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n  File \"/tmp/venv_archinstall/lib/python3.11/site-packages/archinstall/scripts/guided.py\", line 254, in <module>\n    fs_handler.perform_filesystem_operations()\n  File \"/tmp/venv_archinstall/lib/python3.11/site-packages/archinstall/lib/disk/filesystem.py\", line 28, in perform_filesystem_operations\n    if self._disk_config.config_type == DiskLayoutType.Pre_mount:\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'config_type'",
    "stderr_lines": [
        "Traceback (most recent call last):",
        "  File \"/tmp/venv_archinstall/bin/archinstall\", line 8, in <module>",
        "    sys.exit(run_as_a_module())",
        "             ^^^^^^^^^^^^^^^^^",
        "  File \"/tmp/venv_archinstall/lib/python3.11/site-packages/archinstall/__init__.py\", line 291, in run_as_a_module",
        "    importlib.import_module(mod_name)",
        "  File \"/usr/lib/python3.11/importlib/__init__.py\", line 126, in import_module",
        "    return _bootstrap._gcd_import(name[level:], package, level)",
        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"<frozen importlib._bootstrap>\", line 1204, in _gcd_import",
        "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load",
        "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked",
        "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked",
        "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module",
        "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed",
        "  File \"/tmp/venv_archinstall/lib/python3.11/site-packages/archinstall/scripts/guided.py\", line 254, in <module>",
        "    fs_handler.perform_filesystem_operations()",
        "  File \"/tmp/venv_archinstall/lib/python3.11/site-packages/archinstall/lib/disk/filesystem.py\", line 28, in perform_filesystem_operations",
        "    if self._disk_config.config_type == DiskLayoutType.Pre_mount:",
        "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "AttributeError: 'NoneType' object has no attribute 'config_type'"
```

Config file used:
```
{
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pulseaudio"
    },
    "bootloader": "Grub",
    "config_version": "2.6.3",
    "debug": false,
    "disk_config": null,
    "hostname": "{{ pc_name }}",
    "kernels": [
        "linux"
    ],
    "locale_config": {
        "kb_layout": "br-abnt2",
        "sys_enc": "UTF-8",
        "sys_lang": "en_US"
    },
    "mirror_config": {
        "custom_mirrors": [],
        "mirror_regions": {
            "Brazil": [
                "https://mirror.ufscar.br/archlinux/$repo/os/$arch",
                "http://mirror.ufscar.br/archlinux/$repo/os/$arch",
                "http://mirror.ufam.edu.br/archlinux/$repo/os/$arch",
                "http://linorg.usp.br/archlinux/$repo/os/$arch",
                "http://archlinux.c3sl.ufpr.br/$repo/os/$arch"
            ]
        }
    },
    "network_config": {},
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "git",
        "ansible"
    ],
    "parallel downloads": 5,
    "profile_config": {
        "gfx_driver": "All open-source",
        "greeter": "sddm",
        "profile": {
            "custom_settings": {
                "Kde": {}
            },
            "details": [
                "Kde"
            ],
            "main": "Desktop"
        }
    },
    "script": "guided",
    "silent": false,
    "swap": false,
    "timezone": "America/Sao_Paulo",
    "version": "2.6.3"
}
```

**Comment by alan-barzilay** [comment]
Steps to reproduce: mount your devices to /mnt/archinstall and run `archinstall --config  config_path  --creds credentials_path  --silent`


Or as I ran in an ansible playbook:
```

pre_tasks:
    - name: Mkdirs 
      become: true
      ansible.builtin.file:
        path: /mnt/archinstall/scratch
        state: directory
        mode: "0755"
        recurse: true 

    - name: Formatar /dev/sda1 & /dev/sda2
      become: true
      community.general.filesystem:
        fstype: "{{ item.fstype }}"
        dev: "{{ item.dev }}"
      loop:
        - { fstype: "ext4", dev: "/dev/sda1" }
        - { fstype: "swap", dev: "/dev/sda2" }


    - name: Mount sda1 (/) in /mnt/archinstall & sda3 (/scratch) in /mnt/archinstall/scratch
      become: true
      ansible.posix.mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: ext4
        state: mounted
      loop:
        - { path: "/mnt/archinstall", src: "/dev/sda1" }
        - { path: "/mnt/archinstall/scratch", src: "/dev/sda3" }

  tasks:
    - name: Install requirements for archinstall/pip/virtualenv
      become: true
      ansible.builtin.package:
        state: present
        name:
          - pkgconf
          - python-virtualenv
          - python-setuptools
          - python-pip

    - name: Install archinstall with pip
      become: true
      ansible.builtin.pip:
        name: archinstall
        state: present
        virtualenv: "{{ venv }}"

 
    - name: Run archinstall with our client settings
      become: true
      changed_when: true
      ansible.builtin.command: "{{ venv }}/bin/archinstall --config {{ config_path }} --creds {{ credentials }} --silent"
      vars:
        config_path: "/tmp/configuration.json"
        credentials: "/tmp/credentials.json"
```
