### ISSUE TITLE
Mountpoint config and CLI option are ignored

### ISSUE THREAD

**Issue by amezin** [archlinux/archinstall#3474]
### Which ISO version are you using?

2025.05.01

### The installation log

```json
https://github.com/ddterm/gnome-shell-box/actions/runs/15086857151/job/42410479538


    qemu.archlinux: 25h==> ERROR: Failed to install packages to new root
    qemu.archlinux:
    qemu.archlinux: Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt', 'base', 'base-devel', 'linux-firmware', 'linux-lts', 'btrfs-progs', '--noconfirm'] exited with abnormal exit code [1]:  zstd-1.5.7-2  base-3-2  base-devel-1-2
    qemu.archlinux:                btrfs-progs-6.14-1  linux-firmware-20250508.788aadc8-1
    qemu.archlinux:                linux-lts-6.12.28-1
    qemu.archlinux:
    qemu.archlinux: Total Download Size:    653.26 MiB
    qemu.archlinux: Total Installed Size:  1429.42 MiB
    qemu.archlinux:
    qemu.archlinux: :: Proceed with installation? [Y/n]
    qemu.archlinux: error: Partition / too full: 170588 blocks needed, 59382 blocks free
    qemu.archlinux: error: failed to commit transaction (not enough free disk space)
    qemu.archlinux: Errors occurred, no packages were upgraded.
    qemu.archlinux: 25h==> ERROR: Failed to install packages to new root
    qemu.archlinux:
    qemu.archlinux: Pacstrap failed. See /var/log/archinstall/install.log or above message for error details: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt', 'base', 'base-devel', 'linux-firmware', 'linux-lts', 'btrfs-progs', '--noconfirm'] exited with abnormal exit code [1]:  zstd-1.5.7-2  base-3-2  base-devel-1-2
```

#### Description of the issue

Even though I have mountpoint `/mnt/archinstall` set in the config:

https://github.com/ddterm/gnome-shell-box/blob/41390ecf50a25803640e027e7ecc850c7433dfd4/archinstall-config.json:

```
	"disk_config": {
		"config_type": "pre_mounted_config",
		"mountpoint": "/mnt/archinstall"
	},
```

and ALSO pass it as a CLI argument, `archinstall` still runs `pacstrap` in `/mnt` (and fails because there's no free space)

Note: even though I'm using 2025.05.01 ISO, I also run `pacman -Sy --noconfirm archinstall` before attempting installation (because archinstall from `2025.05.01` ISO fails with circular import error). Last time automatic installation succeeded was 2025.03.01

#### Virtual machine config:

https://github.com/ddterm/gnome-shell-box/blob/41390ecf50a25803640e027e7ecc850c7433dfd4/archlinux.pkr.hcl

**Comment by svartkanin** [comment]
When using a pre mounted config we're parsing the path and setting it https://github.com/svartkanin/archinstall/blob/363a96a0a20382001956ebe38b133393d35ba9b9/archinstall/lib/models/device_model.py?plain=1#L101 but it's actually not used as the target installation directory. 

However, the guided script will still use the one from the arguments https://github.com/svartkanin/archinstall/blob/363a96a0a20382001956ebe38b133393d35ba9b9/archinstall/scripts/guided.py?plain=1#L192 which is set to `/mnt` by default https://github.com/svartkanin/archinstall/blob/363a96a0a20382001956ebe38b133393d35ba9b9/archinstall/lib/args.py?plain=1#L50. 

It's true that providing just the configuration will not be sufficient, so that's probably a bug and should set it in the args if provided as a pre-mounted configuration. But providing it explicitly should work.

@amezin there has been a new release 3.0.5 would you mind trying it with that one and specifying it via the arguments explicitly.

**Comment by amezin** [comment]
It is already 3.0.5

> Note: even though I'm using 2025.05.01 ISO, I also run pacman -Sy --noconfirm archinstall before attempting installation (because archinstall from 2025.05.01 ISO fails with circular import error)

```
    qemu.archlinux: :: Synchronizing package databases...
    qemu.archlinux:  core downloading...
    qemu.archlinux:  extra downloading...
    qemu.archlinux: resolving dependencies...
    qemu.archlinux: looking for conflicting packages...
    qemu.archlinux:
    qemu.archlinux: Packages (1) archinstall-3.0.5-1
    qemu.archlinux:
    qemu.archlinux: Total Download Size:   0.76 MiB
    qemu.archlinux: Total Installed Size:  5.48 MiB
    qemu.archlinux: Net Upgrade Size:      0.23 MiB
    qemu.archlinux:
    qemu.archlinux: :: Proceed with installation? [Y/n]
    qemu.archlinux: :: Retrieving packages...
    qemu.archlinux:  archinstall-3.0.5-1-any downloading...
    qemu.archlinux: checking keyring...
    qemu.archlinux: checking package integrity...
    qemu.archlinux: loading package files...
    qemu.archlinux: checking for file conflicts...
    qemu.archlinux: checking available disk space...
    qemu.archlinux: :: Processing package changes...
    qemu.archlinux: upgrading archinstall...
    qemu.archlinux: :: Running post-transaction hooks...
    qemu.archlinux: (1/1) Arming ConditionNeedsUpdate...
```
